title:              Digital interventions for increasing physical activity
email:              emilia.isailovic@student.tugraz.at
description:        Dissecting a metaanalysis on the effectiveness of these technologies in individuals of low socioeconomic status
author:             Emilia Isailovic and Alisa Sinkievich
baseurl:            ""
url:                "https://isailovic-sinkievich.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
